[watch]
ignore = [
    "./static/leptonic",
    "./static/scripts",
]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[tools]
wasm_bindgen = "0.2.87"
wasm_opt = "version_116"
tailwindcss = "3.3.3"